title: "Monika Dybalska | Blog"
author: "Monika Dybalska"
description: "A space to document my coding journey and ongoing projects"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "monika.dybalska@hotmail.com"
github_username: "monikadybalska"
linkedin_username: "monika-dybalska"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
